[package]
name = "hammer-read"
version = "1.0.0"
edition = "2021"

[dependencies]
hammer-core = { path = "../core" }
miette = { workspace = true }
clap = { workspace = true }
nix = { workspace = true }
owo-colors = { workspace = true }
