[package]
name = "hammer-read"
version = "0.9.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
nix = { version = "0.29", features = ["user"] }
anyhow = "1.0"
libc = "0.2"

