[package]
name = "hammer"
version = "0.9.0"
edition = "2021"

[dependencies]
lexopt = "0.3"
owo-colors = "4"
miette = { version = "7", features = ["fancy"] }
reqwest = { version = "0.12", features = ["blocking"] }
open = "5"
which = "6"
figlet-rs = "0.1"
indicatif = "0.17"
thiserror = "1"
