[package]
name = "hammer"
version = "1.0.0"
edition = "2021"

[dependencies]
hammer-core = { path = "../core" }
anyhow = { workspace = true }
lexopt = { workspace = true }
owo-colors = { workspace = true }
nix = { workspace = true }
which = "4.4"
