[package]
name = "hammer-core"
version = "0.9.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
nix = "0.29.0"
chrono = "0.4.38"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
sha2 = "0.10.8"
hex = "0.4.3"
regex = "1.10.5"
